### ISSUE TITLE
fix android compress video bug

### ISSUE THREAD

**Issue by nguyentung158** [Viet20021476/FlutterApp#7]

**Comment by Viet20021476** [comment]
could u give more details about the bug? and which version of Android you have on your simulator/physical device?

**Comment by nguyentung158** [comment]
this issue has appeared while i was using android version 10 on simulator device and android 9 on physical device

**Comment by Viet20021476** [comment]
seems like it did not work on old android version, it works for me on android 12. Try updating to newer android version

**Comment by nguyentung158** [comment]
i tried and successfully deployed video to firebase storage

**Comment by Viet20021476** [comment]
Great
